version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "4040:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'dev'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'dev'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "28000:3306"
volumes:
    mysqldata: {}
